### ISSUE TITLE
stringDedup not exported by package stringdedup

### ISSUE THREAD

**Issue by sni** [lkarlslund/stringdedup#1]
I tried to update from the global predefined dedup singleton to the new type specific way but failed.

What i tried is:

```golang
var dedup *stringdedup.stringDedup[uint32]
func init() {
	dedup = stringdedup.New(func(in []byte) uint32 {
		return xxhash.Checksum32(in)
	})
}

...

func later() {
	dedup.S(...)
}

```

which fails with `stringDedup not exported by package stringdedup`.

Is there any way to use this module without having to pass the global dedup thing around like it was before?

**Comment by lkarlslund** [comment]
The type is unexported because it needs initialization, so I thought it best to do it like that. You can do this in your variable declaration, and not have a func init():

var dedup = stringdedup.New(func(in []byte) uint32 {
	return xxhash.Checksum32(in)
})

**Comment by sni** [comment]
oh man, sorry for such a rookie question. Thanks, this works fine.
